name: Cypress Artifacts and Pages Deployment
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: Cypress Test and Deploy to GitHub Pages
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies and ensure the report directory exists
      - name: Install dependencies
        run: |
          npm install
          npm install cypress-mochawesome-reporter
          mkdir -p cypress/reports

      # Run Cypress with Mochawesome reporter
      - name: Run Cypress tests
        env:
          CYPRESS_firstName: Kazal Chandra 
          CYPRESS_lastName: Barman
        run: |
          npx cypress run --reporter cypress-mochawesome-reporter --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true

      # List reports to verify JSON output
      - name: List reports
        run: ls -la cypress/reports

      # Generate HTML report from Mochawesome JSON
      - name: Generate HTML report
        run: |
          if ls cypress/reports/*.json 1> /dev/null 2>&1; then
            npx mochawesome-merge cypress/reports/*.json -o cypress/reports/report.json
            npx marge cypress/reports/report.json --reportDir ./cypress/reports --inline
          else
            echo "No JSON reports found, skipping report generation."
            exit 1
          fi

      # Upload screenshots on failures
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Upload video always
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CYPRESS_TOKEN }}
          publish_dir: ./cypress/reports
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'kazalbrur'
          user_email: 'kcb.brurcse42@gmail.com'
